# docker-compose.yml
version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./server:/srv/docker-server
          - ./log:/var/log/nginx
          - django_media:/srv/docker-server/media
          - django_static:/srv/docker-server/static 
        depends_on:
          - django

    django:
        container_name: django
        build: ./server
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./server:/srv/docker-server
          - ./log:/var/log/uwsgi
          - django_media:/srv/docker-server/media
          - django_static:/srv/docker-server/static 

volumes:
  django_media:
  django_static:
